ARMmbed/mbed-os-example-blinky

main.cpp
This was only relevant when we were using `Thread::wait` and this sentence was used to emphasize that we were running in our own thread. Not needed anymore now that we use `wait()`.
@AnotherButler
=> Remove the note about wait

mbed-os.lib
Update to the latest mbed OS release. Will be squashed as it does not contain any relevant changes besides lib update.
=> mbed OS 5.4

README.md, main.cpp, mbed_app.json, stats_report.h
Acts as an update to the quick start experience. Moving from:
https://github.com/armmbed/mbed-os-quick-start-blinky to this repo to avoid having old versions floating around.
@janjongboom @bulislaw @SenRamakri
=> Add basic stats reporting to blinky.

README.md, stats_report.h
Reverting 5.11 features from last PR.
@cmonr
=> Revert RAM/ROM reporting segment, went in after 5.10.4

CONTRIBUTING.md, README.md
Merge after 5.11 oob branch is in
Similar to what we have in Mbed OS
This adds:
- inbound-outbound license model
- specifies the license
- adds contributing info (links to our contributing guide)
=> Add contributing references

README.md, main.cpp, mbed_app.json
Issue: https://github.com/ARMmbed/mbed-os-example-blinky/issues/153
=> Set the baudrate to default and reduce prints in blinky

README.md
Compilation log will change from target, toolchain, and release. Better to remove then have outdated or incorrect logs.
@AnotherButler 
@SenRamakri
=> Remove ARMC5 note and compile log

tests/README.md, tests/blinky.log
Add a log compare test for this example for enable example CI testing
=> add log compare test for blinky example

tests/blinky.log
Compiler ID:1 only apply to ARM, we need this working on all the compilers.
=> fix a bug in the log test

main.cpp
This function allows the application to be built wit the bare metal profile without requiring the `rtos-api`.
=> Use `thread_sleep_for` to sleep

.circleci/config.yml, README.md
Added the missing instructions about deploying this example, so that the instructions may be followed and result in working software.
=> README: Correct the instructions for deployment

main.cpp
Fixed the compilation warning by using the Chrono based time argument in `ThisThread::sleep_for` API call.
=> Fix Chrono compilation warnings

CMakeLists.txt
The module has been removed in mbed-os. Add the mbed-os
sub-directory instead to process its `CMakeLists.txt` source
file.
This commit also set the name of the executable target to match
the project name.
Test with: https://github.com/ARMmbed/mbed-os/pull/13378
=> CMake: Do not include the removed mbed-os/cmake/app.cmake module

CMakeLists.txt
The application target can only be configured from
where it has been created. Thus it needs to call the provided
function to apply settings required by Mbed OS.
Depends on: https://github.com/ARMmbed/mbed-os/pull/13413
=> CMake: Call function to setup the application target

CMakeLists.txt
Replace the prefix `mbed_os`_ with the `mbed_` as it is the one used throughout Mbed OS.
Depends on: https://github.com/ARMmbed/mbed-os/pull/13421
=> CMake: Use `mbed_` prefix for CMake functions

.travis.yml, travis-ci/functions.sh
Cache `arm-none-eabi-` compiler to avoid spurious download failures.
Signed-off-by: Devaraj Ranganna <devaraj.ranganna@arm.com>
=> ci: Cache arm-none-eabi- compiler

README.md
Fixes: https://github.com/ARMmbed/mbed-os/issues/13106
This example (mbed-os-example-blinky) requires targets with RTOS support. Bare-metal-targets generally do not have enough memories for this. This PR documents it in README.
=> Document RTOS requirement

.travis.yml, CMakeLists.txt
- Called mbed_set_post_build API for setting post-build operations
=> CMake: Call mbed_set_post_build API for setting post build operations

.travis.yml
In the latest release of Mbed CLI 2 - 4.0.0 the command option has been
changed to ensure good usability.
The `build` command option is been changed to `compile` by keeping
the existing functionality.
Please merge after new Mbedtools release.
=> travis: Update mbedtools `build` to `compile`

README.md
Starting with version 6.5, Mbed OS uses Mbed CLI 2. It uses
Ninja as a build system, and CMake to generate the build environment
and manage the build process in a compiler-independent manner.
=> docs: Add instructions to migrate to Mbed CLI 2

.travis.yml, README.md, mbed-os.lib
This pull request updates the example to be compatible with the 
mbed-os-6.7.0 release of mbed-os.
=> Update for mbed-os-6.7.0

main.cpp
During mbed-os ACI, mbed-os-example-blinky is the basic application compiled for patch validation.
Some targets doesn't have any LED.
Goal is to avoid any specific action for these target validation, this PR will make build OK, and indicate a warning (which can be tracked).
@MarceloSalazar 
NB: this respects https://os.mbed.com/docs/mbed-os/v6.12/apis/standard-pin-names.html
=> ACI: prevent compilation error for targets without any LED

CMakeLists.txt, README.md
This corrects the location of the `.bin` file for CLI 2 in `README.md`, adding the target/profile/toolchain subdirectories.
=> Fix CLI 2 binary location in README
